// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.AzureDevOps.Mcp.Server.Tools.EchoTool.Echo(System.String)~System.String")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.ArtifactsTools")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.EchoTool")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.ReposTools")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.OverviewTools")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.TestPlansTools")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.BoardsTools")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Dotnet.AzureDevOps.Mcp.Server.Tools.PipelinesTools")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.AzureDevOps.Mcp.Server.Tools.BoardsTools.CloseWorkItemsBatchAsync(System.String,System.String,System.String,System.Collections.Generic.IEnumerable{System.Int32},System.String,System.String,System.Boolean,System.Boolean)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyList{Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.WitBatchResponse}}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.AzureDevOps.Mcp.Server.Tools.BoardsTools.AddChildWorkItemsBatchAsync(System.String,System.String,System.String,System.Int32,System.String,System.Collections.Generic.IEnumerable{Dotnet.AzureDevOps.Core.Boards.Options.WorkItemCreateOptions},System.Boolean,System.Boolean)~System.Threading.Tasks.Task{System.Collections.Generic.List{Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.WorkItem}}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.AzureDevOps.Mcp.Server.Tools.BoardsTools.GetQueryAsync(System.String,System.String,System.String,System.String,Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.QueryExpand,System.Int32,System.Boolean,System.Boolean)~System.Threading.Tasks.Task{Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.QueryHierarchyItem}")]
