trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'Dotnet.AzureDevOps.sln'
  sonarProjectKey: 'Chanlabs_Dotnet.AzureDevOps'
  sonarOrganization: 'chanlabs-1'

steps:

# ────────────────────────────── SonarCloud Begin ──────────────────────────────
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarQube'   # Replace with your service connection name
    organization: '$(sonarOrganization)'
    scannerMode: 'dotnet'
    projectKey: '$(sonarProjectKey)'
    projectName: 'Dotnet.AzureDevOps'
    
# ────────────────────────────── Restore Solution ────────────────────────────────
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# ────────────────────────────── Build Solution ────────────────────────────────
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:ExcludePath="test/integration.tests;test/end2end.tests"'
    configuration: '$(buildConfiguration)'
    clean: true
    maximumCpuCount: true

# ────────────────────────────── SonarCloud End ────────────────────────────────
- task: SonarCloudAnalyze@3

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
