name: Build on main

on:
  push:
    branches: [main]          # run only when commits land on main

jobs:
  build:
    runs-on: windows-latest   # same image you used in Azure DevOps
    env:
      buildConfiguration: Release
      solution: Dotnet.AzureDevOps.sln

    steps:
    # ────────────────────────────── Checkout source ─────────────────────────────
    - name: Checkout
      uses: actions/checkout@v4

    # ────────────────────────────── .NET toolchain ─────────────────────────────
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'      # change if your project targets a different SDK

    # ────────────────────────────── Restore packages ───────────────────────────
    - name: Restore packages
      run: dotnet restore "${{ env.solution }}"

    # ────────────────────────────── Build solution ─────────────────────────────
    - name: Build solution (MSBuild)
      run: >
        msbuild "${{ env.solution }}"
        /p:Configuration=${{ env.buildConfiguration }}
        /p:ExcludePath="test/integration.tests;test/end2end.tests"
        /m /restore
