name: Build on main

on:
  push:
    branches: [main]          # run only when commits land on main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ───────────────────── Checkout source ─────────────────────
      - uses: actions/checkout@v4

      # ───────────────────── .NET toolchain ──────────────────────
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # change if your repo targets another SDK

      # ───────────────────── Restore & build ─────────────────────
      - name: Restore packages
        run: dotnet restore Dotnet.AzureDevOps.sln

      - name: Build solution
        run: dotnet build Dotnet.AzureDevOps.sln --configuration Release --no-restore

